select * from customer limit 10

--what is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as revenue
from customer group by gender

--which customer used the discount but still spent more than the avg purchase amount?
select customer_id,purchase_amount from customer
where discount_applied='Yes' and purchase_amount >= (select avg(purchase_amount) from customer)

--top 5 products with the highest avg review rating?
select item_purchased , round(avg(review_rating::numeric),2) as "review_ratings"  --review_rating was double precision type so round func did not worked so we type casted it to numeric and then used round
from customer group by item_purchased order by avg(review_rating) desc limit 5

--compare the avg purchase amounts bw standard and express shipping?
select shipping_type,round(avg(purchase_amount),2) as "average purchase amount" 
from customer group by shipping_type having shipping_type in ('Express','Standard')

--do subscribed customers spend more? compare avg spend and total revenue between subscribed and non subscribed customers?
select subscription_status ,count(customer_id) as "total customer", round(avg(purchase_amount),2) as "average purchase",
sum(purchase_amount) as "revenue" from customer
group by subscription_status 

--which five products have the highest percentage of purchases with discounts applied?
select item_purchased,round(100 * sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer group by item_purchased
order by discount_rate desc limit 5

--segmemnt customers into new,returning and loyal based on their total number of previous purchases, and show the count of each segment
with customer_type as(
select customer_id, previous_purchases, 
case 
when previous_purchases=1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment from customer)
select customer_segment, count(*) as no_of_customers
from customer_type group by customer_segment

--top 3 most purchased products in each category
with item_counts as (select category,item_purchased,count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer group by category,item_purchased)
select item_rank,category,item_purchased,total_orders 
from item_counts
where item_rank <=3